# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Root workspace
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: '⬆️'
  # @odroe/fs
  - package-ecosystem: 'npm'
    directory: '/packages/fs'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: '⬆️'
  # @odroe/fs-local
  - package-ecosystem: 'npm'
    directory: '/packages/local_adapter'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: '⬆️'
  # @odroe/fs-cos
  - package-ecosystem: 'npm'
    directory: '/packages/cos_adapter'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: '⬆️'
  # Example 0
  - package-ecosystem: 'npm'
    directory: '/examples/0.using_fs_adapter'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: '⬆️'
