name: prisma_dmmf
description: This package contains the Prisma DMMF (Data Model Meta Format) which is a JSON representation of the Prisma schema.
version: 1.0.2
repository: https://github.com/odroe/prisma-dmmf

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.1
  path: ^1.8.3
  test: ^1.21.0
